name: Workflow bot discord
on:
  - push
jobs:
  premierJob:
    runs-on: ubuntu-latest
    steps:
      - name: Test hello World
        run: echo "hello world"
  
  TestBot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm test 

